development:
  adapter: postgresql
  encoding: unicode
  database: student_manager_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: student_manager_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: student_manager_production
  pool: 5
